### ISSUE TITLE
32 bit segfaults

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-eng-hin#1]
When run on a 32 bit platform, `echo 'Hubba bubba' | apertium hin-eng` yields `Segmentation fault (core dumped)`

Almost certainly an error somewhere deeper down the pipe, but tracking it here for now. I don't have time to debug it myself.

**Comment by dakshaladia** [comment]
Hi, I would like to help by contributing to this issue

**Comment by TinoDidriksen** [comment]
Sure, how good are you with C++? Come to IRC on Freenode's #apertium

**Comment by dakshaladia** [comment]
Proficiency in C++ :  Intermediate.
Sure. I dropped you a message. Kindly check.

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-lex-tools/issues/53
