### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by knight-95** [apertium/apertium-eng-hin#3]
How can I setup the environment for **apertium** in mac and later contribute to it

**Comment by mr-martian** [comment]
Installation instructions for Mac are at https://wiki.apertium.org/wiki/Apertium_on_Mac_OS_X

General installation issues should be directed to IRC (https://wiki.apertium.org/wiki/IRC) or the mailing list (https://wiki.apertium.org/wiki/Contact) as those are better suited to helping with this type of issue.
